#!/bin/bash
# SOURCE: https://github.com/iridakos/stup
# MIT License
#
# Copyright (c) 2020 Lazarus Lazaridis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#############
# Variables #
#############

# TODO: remove unused
NOTES=()
TEXT_BOLD=$(tput bold)
TEXT_BLACK=$(tput setaf 0)
TEXT_RED=$(tput setaf 1)
TEXT_GREEN=$(tput setaf 2)
TEXT_YELLOW=$(tput setaf 3)
TEXT_LIME_YELLOW=$(tput setaf 190)
TEXT_POWDER_BLUE=$(tput setaf 153)
TEXT_BLUE=$(tput setaf 4)
TEXT_MAGENTA=$(tput setaf 5)
TEXT_CYAN=$(tput setaf 6)
TEXT_WHITE=$(tput setaf 7)
TEXT_BRIGHT=$(tput bold)
TEXT_NORMAL=$(tput sgr0)
TEXT_BLINK=$(tput blink)
TEXT_REVERSE=$(tput smso)
TEXT_UNDERLINE=$(tput smul)
TEXT_NORMAL=$(tput sgr0)
TEXT_GREY=$(tput setaf 248)

# Version
# TODO: update version upon new releases
VERSION="v0.1.1"

# Stup entry point
stup()
{
  resolve_configuration_file
  parse_options "$@"

  if [ -z "$COMMAND" ] && (! [ "$USAGE" = "true" ] ); then
    COMMAND="show"
  fi

  if [ "$COMMAND" != "configure" ] && [ "$USAGE" != "true" ]; then
    ensure_configured
    load_configuration
  fi

  execute
}

######################
# Command executions #
######################

# Issues the execution of the proper command
execute()
{
  if [ "$USAGE" = "true" ]; then
    execute_usage
    return
  fi

  case "$COMMAND" in
    show)
      execute_show
      ;;
    add)
      execute_add
      ;;
    edit)
      execute_edit
      ;;
    configure)
      execute_configure
      ;;
    add_category)
      execute_add_category
      ;;
    list_categories)
      execute_list_categories
      ;;
    order_categories)
      execute_order_categories
      ;;
    set_category_description)
      execute_set_category_description
      ;;
    log)
      execute_log
      ;;
    version)
      execute_version
      ;;
    *)
      print_error "Unknown command: '$COMMAND'"
      exit 1
      ;;
  esac
}

# Shows the notes added for a specific date
execute_show()
{
  if [[ $1 ]]; then
    AT="$1"
  fi

  resolve_date
  extract_date_components

  if [[ $CATEGORY ]]; then
    target_file=$(resolve_target_file "$CATEGORY")

    if [ -f "$target_file" ]; then
      print_info "Displaying notes of category $CATEGORY added for $(success_color "$(display_date "$AT")")."

      local description_file="$REPOSITORY_ROOT/$CATEGORY/description.md"

      if [ -f "$description_file" ]; then
        description="$(emphasize "$(cat $description_file)")"
      else
        description="$(emphasize "# Notes in category: $category")"
      fi

      print_warning "\n>> $description\n"
      sed -e 's/^\-/•/' -e 's/^/  /' "$target_file"

      echo ""
    else
      print_warning "No entries found for $(display_date $AT) in category $CATEGORY."
      echo -e "Do you want to retrieve the last notes added in this category with stup?"
      read -e -p "Type y|Y|yes|Yes or anything else to exit: " search_last_entries

      case "$search_last_entries" in
        y|Y|yes|Yes)
          resolve_last_at
          execute_show "$AT"
          ;;
        *)
          exit 0
      esac
    fi
  else
    load_categories

    # Check if there are any entries for the given date
    local entries_found=false
    for category in "${CATEGORIES[@]}"; do
      local target_file=$(resolve_target_file "$category")

      if [ -f "$target_file" ]; then
        entries_found=true
        break
      fi
    done

    if [ $entries_found == true ]; then
      echo -e "Displaying notes added for $(display_date "$AT")."

      for category in "${CATEGORIES[@]}"; do
        local description_file="$REPOSITORY_ROOT/$category/description.md"
        local target_file=$(resolve_target_file "$category")
        local empty_category=false

        if [ -f "$description_file" ]; then
          description="$(emphasize "$(cat $description_file)")"
        else
          description="$(emphasize "# Notes in category: $category")"
        fi

        if [ -f "$target_file" ]; then
          IFS=$'\n' read -d '' -r -a contents < <(cat "$target_file" | tr -d '[:space:]')

          if [ ${#contents[@]} -eq 0 ]; then
            empty_category=true
          fi
        else
          empty_category=true
        fi

        if [ "$empty_category" = "true" ]; then
          if [ "$INCLUDE_EMPTY" = true ]; then
            print_warning "\n $description\n"
            print_error "   None."
          fi
        else
          print_warning "\n $description\n"
          sed -e 's/^\-/•/' -e 's/^/  /' "$target_file"
        fi
      done

      echo ""
    else
      print_warning "No entries found for $(display_date $AT) in any category."
      echo -e "Do you want to retrieve the last notes added with stup?"
      read -e -p "Type y|Y|yes|Yes or anything else to exit: " search_last_entries

      case "$search_last_entries" in
        y|Y|yes|Yes)
          resolve_last_at
          execute_show "$AT"
          ;;
        *)
          exit 0
      esac
    fi
  fi
}

# Adds notes to a specific date
execute_add()
{
  resolve_required_category
  resolve_date
  extract_date_components

  local number_of_notes=${#NOTES[@]}

  if [ $number_of_notes -eq 0 ]; then
    print_error "You haven't specified any notes to add."
    print_hint "Use the --note or -n flag."
    exit 1
  fi

  target_file="$(resolve_target_file $CATEGORY)"

  if ! [ -f "$target_file" ]; then
    mkdir -p "${target_file%/*}" && touch "$target_file"
  fi

  for item in "${NOTES[@]}"; do
    echo "- $item" >> $target_file
  done

  echo -e "Successfully added $(emphasize "$number_of_notes") notes in category $(emphasize "$CATEGORY") for $(display_date $AT)"
}

# Opens the file keeping the notes of a specific date for edit in user's default editor
execute_edit()
{
  resolve_required_category
  resolve_date
  extract_date_components

  local target_file="$(resolve_target_file "$CATEGORY")"

  print_info "About to edit: $target_file"

  if ! [ -f "$target_file" ]; then
    print_warning "Notes for category "$CATEGORY" on $(display_date "$AT") does not exist."
    read -e -p ">>> Type yes|y to create and edit the file or anything else to abort: " response

    if ! [[ "$response" = 'y' || "$response" = 'yes' ]]; then
      echo 'Aborted.'
      exit 0
    fi
  fi

  local target_directory="$(dirname "$target_file")"
  mkdir -p "$target_directory"

  if [ -z "$STUP_EDITOR" ]; then
    STUP_EDITOR="vi"
  fi

  $STUP_EDITOR "$target_file"
}

# Adds a category
execute_add_category()
{
  if [ -z "$CATEGORY_NAME" ]; then
    print_error "Missing required argument --category-name"
    exit 1
  fi

  if [ -d "$REPOSITORY_ROOT/$CATEGORY_NAME" ]; then
    print_warning "Category '$CATEGORY_NAME' directory already exists. Ensuring its presence in the categories configuration file as well."
  else
    mkdir -p "$REPOSITORY_ROOT/$CATEGORY_NAME"
    print_success "Successfully created category '$CATEGORY_NAME'"
  fi

  store_category_configuration "$CATEGORY_NAME"

  if ! [ -z "$CATEGORY_DESCRIPTION" ]; then
    echo "$CATEGORY_DESCRIPTION" > "$REPOSITORY_ROOT/$CATEGORY_NAME/description.md"
  fi
}

# Shows current categories
execute_list_categories()
{
  load_categories

  printf '%s\n' "${CATEGORIES[@]}"
}

# Opens the categories configuration file for edit
execute_order_categories()
{
  local conf="$(resolve_categories_configuration_file)"

  if ! [ -f "$conf" ]; then
    print_error "problem"
    exit 1
  fi

  if [ -z "$STUP_EDITOR" ]; then
    STUP_EDITOR="vi"
  fi

  $STUP_EDITOR "$conf"
}

# Updates the description of a given category
execute_set_category_description()
{
  if [ -z "$CATEGORY_DESCRIPTION" ]; then
    echo "Missing required argument --category-description"
    exit 1
  fi

  if [ -z "$CATEGORY" ]; then
    echo "No category specified. Changing the default: $DEFAULT_CATEGORY"
    CATEGORY="$DEFAULT_CATEGORY"
  fi

  echo -e "$CATEGORY_DESCRIPTION" > "$REPOSITORY_ROOT/$CATEGORY/description.md"
}

# Configures stup via a wizard
execute_configure()
{
  if ! [ -f "$CONFIG_FILE" ]; then
    fist_time=true
    touch -a "$CONFIG_FILE"
    echo -e "categories_root=$HOME/stup\ndefault_category=personal\n" >> $CONFIG_FILE
  fi

  load_configuration

  wizard "categories_root"
  wizard "default_category"
  wizard "stup_editor"

  store_configuration

  exit 0
}

# Logs note entries per date/category
execute_log()
{
  load_categories
  extract_from_to_dates

  IFS=$'\n' read -d '' -r dates < <(find $REPOSITORY_ROOT -path "$REPOSITORY_ROOT/*/*/*/*.md" | sed -e 's/.*\///' -e 's/\.[^.]*$//' | sort -u -r)

  if (! [ -z "$FROM_AT" ] && ! [ -z "$TO_AT" ]); then
    echo -e "$(print_info "Displaying notes from") $(display_date "$FROM_AT") $(print_info "to") $(display_date "$TO_AT")"
  elif ! [ -z "$FROM_AT" ]; then
    echo -e "$(print_info "Displaying notes from") $(display_date "$FROM_AT") $(print_info "and after")"
  elif ! [ -z "$TO_AT" ]; then
      echo -e "$(print_info "Displaying notes until") $(display_date "$TO_AT")"
  else
    echo -e "$(print_info "Displaying all notes")"
  fi

  local target_categories

  if [ -n "$CATEGORY" ]; then
    target_categories=("$CATEGORY")
  else
    target_categories=( "${CATEGORIES[@]}" )
  fi

  local output=""

  for current_date in ${dates[@]}; do
    if ! (([[ -z "$FROM_AT" ]] || [[ "$current_date" = "$FROM_AT" ]] || [[ "$current_date" > "$FROM_AT" ]] ) && ([[ -z "$TO_AT" ]] || [[ "$current_date" = "$TO_AT" ]] || [[ "$current_date" < "$TO_AT" ]])); then
      continue
    fi

    AT="$current_date"
    extract_date_components

    local category_count=0
    local category_output=""

    for category in "${target_categories[@]}"; do
      local target_file="$(resolve_target_file "$category")"

      if [ -f "$target_file" ]; then
        category_count=$((category_count + 1))

        if [ "$category_count" -gt "1" ]; then
          category_output+="\n"
        fi

        category_output+="$(printf "%-10s %s" "Category:" "$(print_warning "$category")")"
        category_output+="\n\n"
        category_output+="$(sed -e 's/^-/•/' -e 's/^/           /' "$target_file")\n"
      fi
    done

    if [ -n "$category_output" ]; then
      output+="$(printf "%-10s %s" "Date:" "$(emphasize "$(display_date "$AT")")")"
      output+="\n"
      output+="$category_output"
      output+="\n"
    fi
  done

  if [ -z "$output" ]; then
    print_warning "Nothing found."
  else
    echo -e "\n$output" | more
  fi
}

# Prints usage information
execute_usage()
{
  local output;

  if [ -z "$COMMAND" ]; then
    output="$(show_usage_all)"
  else
    output=$("show_usage_$COMMAND")
  fi

  echo "$output" | more
}

execute_version()
{
  echo "stup version $VERSION"
}

##########################
# Command helper methods #
##########################

# Ensures stup is configured
ensure_configured()
{
  if ! [ -f "$CONFIG_FILE" ]; then
    print_error "Failed to find configuration file: $CONFIG_FILE"
    print_hint "Have you configured stup? If not, use: stup configure"
    exit 1
  fi

  load_configuration

  if [ -z "$REPOSITORY_ROOT" ]; then
    print_error "Invalid stup configuration - missing categories root"
    print_hint "Use \"stup --configure\" to re-configure stup"
    exit 1
  fi

  if [ -z "$DEFAULT_CATEGORY" ]; then
    print_error "Invalid stup configuration - missing default category"
    print_hint "Use \"stup --configure\" to re-configure stup"
    exit 1
  fi

  if ! [ -d "$REPOSITORY_ROOT" ]; then
    print_error "Invalid stup configuration - categories root directory does not exist"
    print_hint "Use \"stup --configure\" to re-configure stup"
    exit 1
  fi

  if ! [ -f "$(resolve_categories_configuration_file)" ]; then
    print_error "Invalid stup configuration - missing categories configuration file"
    print_hint "Use \"stup --configure\" to re-configure stup"
    exit 1
  fi
}

# Parses the user's options
parse_options()
{
  while [[ $# -gt 0 ]]; do
    case "$1" in
      today|tomorrow|yesterday)
        AT="$1"
        shift
        ;;
      week|month|year|previous-week|previous-month|previous-year)
        FROM_TO_ALIAS="$1"
        shift
        ;;
      --from)
        FROM_AT="$2"
        shift 2
        ;;
      --to)
        TO_AT="$2"
        shift 2
        ;;
      --add|add)
        COMMAND="add"
        shift
        ;;
      --show|show)
        COMMAND="show"
        shift
        ;;
      --include-empty)
        INCLUDE_EMPTY=true
        shift
        ;;
      --edit|edit)
        COMMAND="edit"
        shift
        ;;
      @|-@|--at)
        AT="$2"
        shift 2
        ;;
      -h|--help|usage)
        USAGE="true"
        shift
        ;;
      --add-category|add-category)
        COMMAND="add_category"
        shift
        ;;
      --order-categories|order-categories)
        COMMAND="order_categories"
        shift
        ;;
      --set-category-description|set-category-description)
        COMMAND="set_category_description"
        shift
        ;;
      --list-categories|list-categories|categories)
        COMMAND="list_categories"
        shift
        ;;
      --category-name)
        CATEGORY_NAME="$2"
        shift 2
        ;;
      --category-description)
        CATEGORY_DESCRIPTION="$2"
        shift 2
        ;;
      -c|--category)
        load_configuration
        load_categories

        if [[ ! " ${CATEGORIES[@]} " =~ " ${2} " ]]; then
          print_error "Category "$2" does not exist."
          exit 1
        fi

        CATEGORY="$2"
        shift 2
        ;;
      -n|--note)
        NOTES+=("$2")
        shift 2
        ;;
      --configure|configure)
        COMMAND="configure"
        shift
        ;;
      --log|log)
        COMMAND="log"
        shift
        ;;
      --) # end argument parsing
        shift
        break
        ;;
      -v|--version)
        COMMAND="version"
        shift
        ;;
      -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *)
        echo "Error: Unknown command \"$1\"" >&2
        exit 1
        ;;
    esac
  done
}

# Starts the configuration wizard
wizard()
{
  case "$1" in
    categories_root)
      if [ -z "$REPOSITORY_ROOT" ]; then
        REPOSITORY_ROOT="$HOME/stup"
      fi

      if [[ "$2" ]]; then
        print_error "$2"
      else
        print_info "Please specify which directory stup will be using to store your notes."
        print_info "By default, the notes will be stored in $REPOSITORY_ROOT."
      fi

      read -e -p ">>> Press enter to use the default location or fill in your desired destination: " new_category_root
      new_category_root=$(echo -e "${new_category_root}" | tr -d '[:space:]')

      case "$new_category_root" in
        "")
          print_success "Keeping default directory."
          mkdir -p "$REPOSITORY_ROOT"
          touch -a "$(resolve_categories_configuration_file)"
          ;;
        *)
          {
            new_category_root="${new_category_root/#\~/$HOME}"
            new_category_root=$(readlink -f "$new_category_root")

            mkdir -p "$new_category_root"

            new_category_root=$(builtin cd "$new_category_root" 2>/dev/null && pwd)

            if [[ -d "$new_category_root" ]]; then
              REPOSITORY_ROOT="$new_category_root"
              touch -a "$(resolve_categories_configuration_file)"
            else
              wizard "categories_root" "Failed to create the new category root."
            fi
          } || {
            wizard "categories_root" "Failed to create the new category root, make sure it's a valid path."
          }
          ;;
      esac
      ;;
    default_category)
      if [ -z "$DEFAULT_CATEGORY" ]; then
        DEFAULT_CATEGORY="personal"
      fi

      if [[ "$2" ]]; then
        print_error "$2"
      else
        print_info "Please specify which category will be your default one (if you have many)."
        print_info "The default category is currently set to \"$DEFAULT_CATEGORY\"."
      fi

      read -e -p ">>> Press enter to keep the default or fill in a new one (ex. review): " new_default_category
      new_default_category=$(echo -e "${new_default_category}" | tr -d '[:space:]')

      case "$new_default_category" in
        "")
          print_success "Default category still set to \"$DEFAULT_CATEGORY\"."
          store_category_configuration "$DEFAULT_CATEGORY"
          ;;
        *)
          {
            mkdir -p "$REPOSITORY_ROOT/$new_default_category"

            if [[ -d "$REPOSITORY_ROOT/$new_default_category" ]]; then
              DEFAULT_CATEGORY="$new_default_category"
              print_success "Default category set to $DEFAULT_CATEGORY"
              store_category_configuration "$DEFAULT_CATEGORY"
            else
              wizard "default_category" "Failed to create the default category's directory. Make sure the name is also a valid directory name."
            fi
          } || {
            wizard "default_category" "Failed to create the directory for the new default category. Make sure the name is also a valid directory name."
          }
          ;;
      esac
      ;;
    stup_editor)
      if [ -z "$STUP_EDITOR" ]; then
        STUP_EDITOR="vi"
      fi

      if [[ "$2" ]]; then
        print_error "$2"
      else
        print_info "Please specify which editor you want to use when manually editing your notes."
        print_info "The default editor is currently set to \"$STUP_EDITOR\"."
      fi

      read -e -p ">>> Press enter to keep the default or fill in a new one (ex. vim): " new_stup_editor
      new_stup_editor=$(echo -e "${new_stup_editor}" | tr -d '[:space:]')

      if ! [[ -z "$new_stup_editor" ]]; then
        STUP_EDITOR="$new_stup_editor"
        print_success "Stup editor set to: $STUP_EDITOR"

      else
        print_success "Keeping the default editor: $STUP_EDITOR."
      fi
  esac
}

# Loads the stup configuration
load_configuration()
{
  if [[ $CONFIGURATION_LOADED == true ]]; then
    return
  fi

  if [ -z CONFIG_FILE ]; then
    print_error "Configuration file not found."
    print_hint "Have you configured stup?"
    exit 1
  fi

  while IFS='=' read variable_name variable_value
  do
    if [[ $variable_value ]]
    then
      handle_configuration_variable "$variable_name" "$variable_value"
    fi
  done < $CONFIG_FILE

  CONFIGURATION_LOADED=true
}

# Loads the configuration variables
handle_configuration_variable()
{
  case "$1" in
    categories_root)
      REPOSITORY_ROOT="$2"
      ;;
    default_category)
      DEFAULT_CATEGORY="$2"
      ;;
    stup_editor)
      STUP_EDITOR="$2"
      ;;
  esac
}

# Resolves the location of the stup configuration file
resolve_configuration_file()
{
  CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/stup.conf"
}

# Stores configuration of stup
store_configuration()
{
  echo -e "categories_root=$REPOSITORY_ROOT
default_category=$DEFAULT_CATEGORY
stup_editor=$STUP_EDITOR
" > $CONFIG_FILE
}

store_category_configuration()
{
  load_categories

  local category_to_store="$1"

  if ! $(array_contains CATEGORIES "$category_to_store") ; then
    echo "$category_to_store" >> "$(resolve_categories_configuration_file)"
  fi
}

# Properly sets the current category to the default one unless already specified
resolve_required_category()
{
  if [[ -z "$CATEGORY" ]]; then
    CATEGORY="$DEFAULT_CATEGORY"
  fi
}

# Properly sets year, month and day based on the specified AT variable
# TODO: print error on invalid date format
extract_date_components()
{
  case "$AT" in
    today|yesterday|tomorrow)
      YEAR=$(date -d "$AT" +"%Y")
      MONTH=$(date -d "$AT" +"%m")
      DAY=$(date -d "$AT" +"%d")
      ;;
    *)
      IFS='-' read -ra parts <<< "$AT"
      YEAR="${parts[0]}"
      MONTH="${parts[1]}"
      DAY="${parts[2]}"
      ;;
  esac
}

# Properly sets from and to dates based on aliases
extract_from_to_dates()
{
  case "$FROM_TO_ALIAS" in
    week)
      FROM_AT=$(date -d "$(date -d yesterday +%u) days ago" +"%Y-%m-%d")
      TO_AT=$(date -d "$FROM_AT + 6 days" +"%Y-%m-%d")
      ;;
    previous-week)
      local first_date_of_current_week=$(date -d "$(date -d yesterday +%u) days ago" +"%Y-%m-%d")
      FROM_AT=$(date -d "$first_date_of_current_week -7 days" +"%Y-%m-%d")
      TO_AT=$(date -d "$first_date_of_current_week -1 days" +"%Y-%m-%d")
      ;;
    month)
      FROM_AT=$(date +"%Y-%m-01")
      TO_AT=$(date -d "$(date -d "today + 1 month" +"%Y-%m-01") - 1 day" +"%Y-%m-%d")
      ;;
    previous-month)
      FROM_AT=$(date -d "$(date +'%Y-%m-01') - 1 month" +"%Y-%m-%d")
      TO_AT=$(date -d "$(date +'%Y-%m-01') - 1 second" +"%Y-%m-%d")
      ;;
    year)
      FROM_AT=$(date -d "today" +"%Y-01-01")
      TO_AT=$(date -d "today" +"%Y-12-31")
      ;;
    previous-year)
      FROM_AT=$(date -d "today - 1 year" +"%Y-01-01")
      TO_AT=$(date -d "today - 1 year" +"%Y-12-31")
      ;;
    "")
      ;;
    *)
      print_warning "I don't know how to handle $FROM_TO_ALIAS"
      ;;
  esac
}

# Loads the currently registered categories
load_categories()
{
  IFS=$'\n' read -d '' -r -a CATEGORIES < "$(resolve_categories_configuration_file)"
}

# Checks if array has an element
# https://stackoverflow.com/a/14367368/2292448
array_contains () {
  local array="$1[@]"
  local seeking=$2
  for element in "${!array}"; do
    [[ $element == "$seeking" ]] && return
  done

  false
}

# Sets the default date per action if not specified by the user
resolve_date()
{
  if [ ! -z "$AT" ]; then
    return
  fi

  case "$COMMAND" in
    show)
      AT="yesterday"
      ;;
    add|edit)
      AT="today"
      ;;
    *)
      print_warning "I don't know how to handle default date for command: $COMMAND"
      ;;
  esac
}

# Retrieves the last date a note was issued before a specified date
resolve_last_at()
{
  local year=$YEAR,month=$MONTH,day=$DAY,last_at=""
  local target_path=""
  local current_target_file=$(basename $(resolve_target_file))
  local winner=""
  local current_at="$AT"
  AT=""

  # TODO: optimize this search, it can get too big with the increase of entries
  ########################
  # search in month days #
  ########################
  if [[ $CATEGORY ]]; then
    target_path="$REPOSITORY_ROOT/$CATEGORY/$YEAR/$MONTH"
  else
    target_path="$REPOSITORY_ROOT/*/$YEAR/$MONTH"
  fi

  while IFS= read -r filename; do
    if [[ "$current_target_file" > "$filename" ]]; then
      AT="${filename%.*}"
      return
    fi
  done < <(find $REPOSITORY_ROOT -path "$target_path/*.md" -printf "%f\n" | sort -r)

  #########################
  # search in year months #
  #########################
  if [[ $CATEGORY ]]; then
    target_path="$REPOSITORY_ROOT/$CATEGORY/$YEAR/*"
  else
    target_path="$REPOSITORY_ROOT/*/$YEAR/*"
  fi

  while IFS= read -r filename; do
    if [[ "$current_target_file" > "$filename" ]]; then
      AT="${filename%.*}"
      return
    fi
  done < <(find $REPOSITORY_ROOT -path "$target_path/*.md" -printf "%f\n" | sort -r)

  ###################
  # search in years #
  ###################
  if [[ $CATEGORY ]]; then
    target_path="$REPOSITORY_ROOT/$CATEGORY/*/*"
  else
    target_path="$REPOSITORY_ROOT/*/*/*"
  fi

  while IFS= read -r filename; do
    if [[ "$current_target_file" > "$filename" ]]; then
      AT="${filename%.*}"
      return
    fi
  done < <(find $REPOSITORY_ROOT -path "$target_path/*.md" -printf "%f\n" | sort -r)

  # Exit if no previous notes file found.
  if [ -z "$AT" ]; then
    print_warning "No entries found prior to $(display_date "$current_at")."
    exit 0
  fi
}

# Displays human date in green
# TODO: must find a better way for handling colored output
display_date()
{
  echo $(success_color "$(date --date "$1" +"%A %B %d, %Y")")
}

# Resolves the filename of the stup entry for a specific date at a specific category
resolve_target_file()
{
  echo "$REPOSITORY_ROOT/$1/$YEAR/$MONTH/$YEAR-$MONTH-$DAY.md"
}

# Resolves the filename of the categories configuration
resolve_categories_configuration_file()
{
  echo "$REPOSITORY_ROOT/categories.conf"
}

#################
# Usage helpers #
#################

# Shows usage for all commands
show_usage_all()
{
  echo -e "usage: stup command [<options>]"
  echo -e "List of availabe commands:\n"

  echo -e "$(emphasize "show")"
  echo -e "$(show_usage_show)" | sed -e 's/^/  /'
  echo ""
  echo -e "$(emphasize "add")"
  echo -e "$(show_usage_add)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "edit")"
  echo -e "$(show_usage_edit)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "log")"
  echo -e "$(show_usage_log)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "add-category")"
  echo -e "$(show_usage_add_category)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "list-categories")"
  echo -e "$(show_usage_list_categories)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "set-category-description")"
  echo -e "$(show_usage_set_category_description)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "order-categories")"
  echo -e "$(show_usage_order_categories)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "usage")"
  echo -e "$(show_usage_usage)" | sed -e 's/^/  /'

  echo ""
  echo -e "$(emphasize "version")"
  echo -e "$(show_usage_version)" | sed -e 's/^/  /'
}

# Shows usage for the show command
show_usage_show()
{
  echo -e "Shows notes for a specific date.
This is the default stup command being executed if none is specified.\n
usage: stup show [<options>]\n
List of available options:"

  printf "\n%15s   %s" "@, -@, --at"     "Specifies the date whose notes will be shown."
  printf "\n%15s   %s" " "               "The date can be explicit in the format YYYY-MM-DD"
  printf "\n%15s   %s" " "               "or one of the aliases: yesterday, today, tomorrow"
  printf "\n%15s   %s" " "               "If you omit setting a date, stup will show yesterday's notes by default."
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup show @ today"
  printf "\n%15s   %s" " "               "  stup show @ 2020-04-18"
  printf "\n%15s   %s" "yesterday"       "Alias to set the date to yesterday"
  printf "\n%15s   %s" " "               "Example: stup show yesterday"
  printf "\n%15s   %s" "today"           "Alias to set the date to today"
  printf "\n%15s   %s" " "               "Example: stup show today"
  printf "\n%15s   %s" "tomorrow"        "Alias to set the date to tomorrow"
  printf "\n%15s   %s" " "               "Example: stup show tomorrow"
  printf "\n%15s   %s" "-c, --category" "Specifies the category whose notes will be shown."
  printf "\n%15s   %s" " "              "If omitted, notes from all categories will be shown"
  printf "\n%15s   %s" " "              "Example: stup show -c work"
}

# Shows usage for the add command
show_usage_add()
{
  echo -e "Adds notes for a specific date to a specific category.
usage: stup add [<options>]\n
List of available options:"

  printf "\n%15s   %s" "@, -@, --at"     "Specifies in which date stup will add the notes."
  printf "\n%15s   %s" " "               "The date can be explicit in the format YYYY-MM-DD"
  printf "\n%15s   %s" " "               "or one of the aliases: yesterday, today, tomorrow"
  printf "\n%15s   %s" " "               "If you omit setting a date, stup will add the note(s) in today's date."
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup add @ today ..."
  printf "\n%15s   %s" " "               "  stup add @ 2020-04-18 ..."
  printf "\n%15s   %s" "yesterday"       "Alias to set the date to yesterday"
  printf "\n%15s   %s" " "               "Example: stup add yesterday ..."
  printf "\n%15s   %s" "today"           "Alias to set the date to today"
  printf "\n%15s   %s" " "               "Example: stup add today ..."
  printf "\n%15s   %s" "tomorrow" "Alias to set the date to tomorrow"
  printf "\n%15s   %s" " "               "Example: stup add tomorrow ..."
  printf "\n%15s   %s" "-c, --category" "Specifies the category in which stup will save the notes."
  printf "\n%15s   %s" " "               "If omitted, notes will be saved in your default category"
  printf "\n%15s   %s" " "               "Example: stup add -c work ..."
  printf "\n%15s   %s" "-n, --note"      "Specifies the note to be added."
  printf "\n%15s   %s" " "               "This is a repeatable option so you may set it multiple times to add more than"
  printf "\n%15s   %s" " "               "one notes at once."
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup add today -n \"a note\""
  printf "\n%15s   %s" " "               "  stup add @ 2020-10-05 -n \"first note\" -n \"second note\""
}

# Shows usage for the edit command
show_usage_edit()
{
  echo -e "Opens user's editor to manually edit notes for a specific date and category.
usage: stup edit [<options>]\n
List of available options:"

  printf "\n%15s   %s" "@, -@, --at"     "Specifies the date whose notes will be manually edited."
  printf "\n%15s   %s" " "               "The date can be explicit in the format YYYY-MM-DD"
  printf "\n%15s   %s" " "               "or one of the aliases: yesterday, today, tomorrow"
  printf "\n%15s   %s" " "               "If you omit setting a date, stup will default to today's date."
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup edit @ today ..."
  printf "\n%15s   %s" " "               "  stup edit @ 2020-04-18 ..."
  printf "\n%15s   %s" "yesterday"       "Alias to set the date to yesterday"
  printf "\n%15s   %s" " "               "Example: stup edit yesterday ..."
  printf "\n%15s   %s" "today"           "Alias to set the date to today"
  printf "\n%15s   %s" " "               "Example: stup edit today ..."
  printf "\n%15s   %s" "tomorrow" "Alias to set the date to tomorrow"
  printf "\n%15s   %s" " "               "Example: stup edit tomorrow ..."
  printf "\n%15s   %s" "-c, --category" "Specifies the category whose notes will be manually edited."
  printf "\n%15s   %s" " "               "If omitted, stup will use your default category"
  printf "\n%15s   %s" " "               "Example: stup edit -c work ..."
}

# Shows usage for the log command
show_usage_log()
{
  echo -e "Lists all notes for a period of time per date and category.
usage: stup log [<options>]\n
List of available options:"

  printf "\n%15s   %s" "-f, --from"      "Specifies to list the notes from a specific date and after"
  printf "\n%15s   %s" " "               "The date can be explicit in the format YYYY-MM-DD"
  printf "\n%15s   %s" " "               "or one of the aliases: yesterday, today, tomorrow"
  printf "\n%15s   %s" " "               "You may omit this option."
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup log --from today --to 2020-08-10"
  printf "\n%15s   %s" " "               "  stup log --from 2019-04-18 --to today"
  printf "\n%15s   %s" "-t, --to"       "Specifies to list the notes added before a specific date"
  printf "\n%15s   %s" " "               "The date can be explicit in the format YYYY-MM-DD"
  printf "\n%15s   %s" " "               "or one of the aliases: yesterday, today, tomorrow"
  printf "\n%15s   %s" " "               "You may omit this option"
  printf "\n%15s   %s" " "               "Examples:"
  printf "\n%15s   %s" " "               "  stup log --from today --to 2020-08-10"
  printf "\n%15s   %s" " "               "  stup log --from 2019-04-18 --to today"
  printf "\n%15s   %s" "week"            "Alias to list the notes of current week"
  printf "\n%15s   %s" " "               "Example: stup log week"
  printf "\n%15s   %s" "previous-week"   "Alias to list the notes of previous week"
  printf "\n%15s   %s" " "               "Example: stup log previous-week"
  printf "\n%15s   %s" "month"            "Alias to list the notes of current month"
  printf "\n%15s   %s" " "               "Example: stup log month"
  printf "\n%15s   %s" "previous-month"  "Alias to list the notes of current previous-month"
  printf "\n%15s   %s" " "               "Example: stup log previous-month"
  printf "\n%15s   %s" "year"            "Alias to list the notes of current year"
  printf "\n%15s   %s" " "               "Example: stup log year"
  printf "\n%15s   %s" "previous"        "Alias to list the notes of previous-year"
  printf "\n%15s   %s" " "               "Example: stup log previous-year"
  printf "\n%15s   %s" "-c, --category"  "Specifies the category whose notes will be listed."
  printf "\n%15s   %s" " "               "If omitted, stup will list the notes of all categories."
  printf "\n%15s   %s" " "               "Example: stup log -c work week"
}

# Shows usage for the add category command
show_usage_add_category()
{
  echo -e "Adds a new category.
usage: stup add-category [<options>]\n
List of available options:"

  printf "\n%25s   %s" "--category-name"        "Specifies the name of the category"
  printf "\n%25s   %s" " "                      "Example: stup add-category --category-name \"meetings\""
  printf "\n%25s   %s" "--category-description" "Specifies the description of the category"
  printf "\n%25s   %s" " "                      "Example: stup add-category --category-name \"meetings\""
  printf "\n%25s   %s" " "                      "         --category-description \"Meetings\""
}

# Shows usage for the set category description command
show_usage_set_category_description()
{
  echo -e "Sets a description for a category.
usage: stup set-category-description [<options>]\n
List of available options:"

  printf "\n%25s   %s" "-c, --category"         "Specifies the name of the category whose description will change"
  printf "\n%25s   %s" " "                      "If omitted, stup will change the description of the default category"
  printf "\n%25s   %s" " "                      "Example: stup set-category-description -c \"meetings\""
  printf "\n%25s   %s" "--category-description" "Specifies the new description of the category"
  printf "\n%25s   %s" " "                      "Example: stup set-category-description -c \"meetings\""
  printf "\n%25s   %s" " "                      "         --category-description \"Work meetings\""
}

# Shows usage for the order categories command
show_usage_order_categories()
{
  echo -e "Opens the categories file for manual editing to change their order.
usage: stup order-categories\n"

  echo -e "This command doesn't have any options."
  echo -e "Changing the order of the categories inside the file will change the order that"
  echo -e "stup uses to display the notes."
}

# Shows usage for the list categories command
show_usage_list_categories()
{
  echo -e "Shows a list with your current categories.
usage: stup list-categories\n"

  echo -e "This command doesn't have any options."
}

# Shows usage for the usage command
show_usage_usage()
{
  echo -e "Shows usage information.
usage: stup <command> usage
       stup <command> -h
       stup <command> --help\n"

  printf "\n%15s   %s" "<command>"         "Specifies the name of the category whose description will change"
  printf "\n%15s   %s" " "                 "If omitted, stup will show usage information for all commands."
  printf "\n%15s   %s" " "                 "Examples:"
  printf "\n%15s   %s" " "                 "  stup add usage"
  printf "\n%15s   %s" " "                 "  stup add -h"
  printf "\n%15s   %s" " "                 "  stup add --help"
  printf "\n%15s   %s" " "                 "  stup usage\n"
}

show_usage_version()
{
  echo -e "Shows stup version.
usage: stup -v
       stup --version\n"
}

#####################
# UI Helper methods #
#####################

print_error()
{
  echo -e "${TEXT_RED}$1${TEXT_NORMAL}"
}

print_warning()
{
  echo -e "${TEXT_YELLOW}$1${TEXT_NORMAL}"
}

print_hint()
{
  echo -e "${TEXT_POWDER_BLUE}$1${TEXT_NORMAL}"
}

print_info()
{
  echo -e "${TEXT_GREY}$1${TEXT_NORMAL}"
}

print_success()
{
  echo -e "${TEXT_GREEN}$1${TEXT_NORMAL}"
}

success_color()
{
  echo "${TEXT_GREEN}$1${TEXT_NORMAL}"
}

emphasize()
{
  echo "${TEXT_BOLD}$1${TEXT_NORMAL}"
}

# Let's go
stup "$@"; exit
